services:
  backend:
    build:
      context: ./backend

    container_name: kaamwala-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend

    container_name: kaamwala-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend
